### PR TITLE
How to use Git, PRs, commits, code review, and proper documentation

### PR DESCRIPTION
**Pull request by lkwatson**
Review the revert that reverted the original merge of the PR, yo.

(Review this PR properly. Thanks @sarah256.)

### CODE REVIEW

**Review by NoahNaiman — APPROVED** [review]
Approved update of README

**Review by sarah256 — APPROVED** [review]

**Review by warren — APPROVED** [review]
LGTM!

**Review by maridematte — APPROVED** [review]

**Review by mhendrick98 — APPROVED** [review]

**Review by alexfarra — APPROVED** [review]

**Review by puzzledsean — APPROVED** [review]

**Review by emampons — COMMENTED** [review]
looks good now, still need to add guidelines for specific languages, will make PRs easier if everyone knows what the code is supposed to look like

**Review by emampons — APPROVED** [review]

**Comment by sarah256** [comment]
@emampons i plan to add that in a separate PR! :) i figure i can talk to project leads about the languages they are using and come up with something -- i already have some python standards written but i think thats just applicable for my team

**Comment by lkwatson** [comment]
Re: Python and other languages, can we point to PEP8 and normal language standards?
For documentation, might be nice to use something standard like Doxygen.

**Comment by sarah256** [comment]
@lkwatson yea for sure! I was thinking about using Sphynx for Python, because it automatically generates documentation.  Emmanuel and I are going to discuss before the meeting, if you'd like to join!

**Pull request merged**
